import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FileCode2, GitFork, PenLine, Terminal } from "lucide-react";
import { useCodeIntelRuntime } from "../app/hooks/useCodeIntelRuntime";
import { CodeIntelArcDiagram } from "./CodeIntelArcDiagram";
import { CodeIntelTreemap } from "./CodeIntelTreemap";
import { ActionButton } from "./ui/ActionButton";
export const CodeIntelPrimaryView = ({ enabled }) => {
    const { events, treemapRoot, couplingData, isLoading, error, refresh } = useCodeIntelRuntime(enabled);
    if (isLoading && events.length === 0) {
        return (_jsx("section", { className: "code-intel-view", "aria-label": "Code Intel primary view", children: _jsx("section", { className: "code-intel-panel", children: _jsxs("header", { className: "code-intel-panel-header", children: [_jsx("h2", { children: "Code Intel" }), _jsx("p", { children: "Loading edit events..." })] }) }) }));
    }
    if (error) {
        return (_jsx("section", { className: "code-intel-view", "aria-label": "Code Intel primary view", children: _jsx("section", { className: "code-intel-panel", children: _jsxs("header", { className: "code-intel-panel-header", children: [_jsx("h2", { children: "Code Intel" }), _jsx("p", { className: "code-intel-error", children: error })] }) }) }));
    }
    if (events.length === 0) {
        return (_jsx("section", { className: "code-intel-view", "aria-label": "Code Intel primary view", children: _jsx("section", { className: "code-intel-panel", children: _jsxs("header", { className: "code-intel-panel-header", children: [_jsx("h2", { children: "Code Intel" }), _jsx("p", { children: "No edit events recorded yet. Events are tracked as agents edit files." })] }) }) }));
    }
    return (_jsxs("section", { className: "code-intel-view", "aria-label": "Code Intel primary view", children: [_jsxs("header", { className: "code-intel-view-header", children: [_jsxs("span", { className: "code-intel-stat", children: [_jsx(PenLine, { size: 13, className: "code-intel-stat-icon code-intel-stat-icon--edits" }), _jsx("span", { className: "code-intel-stat-value", children: events.length }), _jsx("span", { className: "code-intel-stat-label", children: "edits" })] }), _jsxs("span", { className: "code-intel-stat", children: [_jsx(FileCode2, { size: 13, className: "code-intel-stat-icon code-intel-stat-icon--files" }), _jsx("span", { className: "code-intel-stat-value", children: couplingData?.files.length ?? 0 }), _jsx("span", { className: "code-intel-stat-label", children: "files" })] }), _jsxs("span", { className: "code-intel-stat", children: [_jsx(Terminal, { size: 13, className: "code-intel-stat-icon code-intel-stat-icon--sessions" }), _jsx("span", { className: "code-intel-stat-value", children: new Set(events.map((e) => e.sessionId)).size }), _jsx("span", { className: "code-intel-stat-label", children: "sessions" })] }), _jsxs("span", { className: "code-intel-stat", children: [_jsx(GitFork, { size: 13, className: "code-intel-stat-icon code-intel-stat-icon--pairs" }), _jsx("span", { className: "code-intel-stat-value", children: couplingData?.pairs.length ?? 0 }), _jsx("span", { className: "code-intel-stat-label", children: "pairs" })] }), _jsx(ActionButton, { size: "dense", variant: "accent", onClick: refresh, children: "Refresh" })] }), _jsxs("div", { className: "code-intel-panels", children: [_jsxs("section", { className: "code-intel-panel code-intel-panel--treemap", children: [_jsxs("header", { className: "code-intel-panel-header", children: [_jsx("h2", { children: "Edit Frequency" }), _jsx("p", { children: "File size = number of edits." })] }), treemapRoot && _jsx(CodeIntelTreemap, { root: treemapRoot })] }), _jsxs("section", { className: "code-intel-panel code-intel-panel--coupling", children: [_jsxs("header", { className: "code-intel-panel-header", children: [_jsx("h2", { children: "Change Coupling" }), _jsx("p", { children: "Files that change together in the same session." })] }), couplingData && _jsx(CodeIntelArcDiagram, { data: couplingData })] })] })] }));
};
