import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TERMINAL_COMPLETION_SOUND_OPTIONS, } from "../app/notificationSounds";
import { ActionButton } from "./ui/ActionButton";
import { SettingsToggle } from "./ui/SettingsToggle";
export const SettingsPrimaryView = ({ terminalCompletionSound, isRuntimeStatusStripVisible, onTerminalCompletionSoundChange, onPreviewTerminalCompletionSound, onRuntimeStatusStripVisibilityChange, }) => (_jsxs("section", { className: "settings-view", "aria-label": "Settings primary view", children: [_jsxs("section", { className: "settings-panel", "aria-label": "Completion notification settings", children: [_jsxs("header", { className: "settings-panel-header", children: [_jsx("h2", { children: "Orchestration completion sound" }), _jsx("p", { children: "Play a notification when a orchestration moves from processing to idle." })] }), _jsx("div", { className: "settings-sound-picker", children: TERMINAL_COMPLETION_SOUND_OPTIONS.map((option) => (_jsxs("button", { "aria-pressed": terminalCompletionSound === option.id, className: "settings-sound-option", "data-active": terminalCompletionSound === option.id ? "true" : "false", onClick: () => {
                            onTerminalCompletionSoundChange(option.id);
                            onPreviewTerminalCompletionSound(option.id);
                        }, type: "button", children: [_jsx("span", { className: "settings-sound-option-label", children: option.label }), _jsx("span", { className: "settings-sound-option-description", children: option.description })] }, option.id))) }), _jsxs("div", { className: "settings-panel-actions", children: [_jsx(ActionButton, { "aria-label": "Preview selected completion sound", className: "settings-sound-preview", onClick: () => {
                                onPreviewTerminalCompletionSound(terminalCompletionSound);
                            }, size: "dense", variant: "accent", children: "Preview" }), _jsx("span", { className: "settings-saved-pill", children: "Saved locally" })] })] }), _jsxs("section", { className: "settings-panel", "aria-label": "Workspace surface visibility settings", children: [_jsxs("header", { className: "settings-panel-header", children: [_jsx("h2", { children: "Workspace surface visibility" }), _jsx("p", { children: "Enable or disable optional surfaces in the main workspace shell." })] }), _jsx("div", { className: "settings-toggle-grid", children: _jsx(SettingsToggle, { label: "Runtime status strip", description: "Top console status strip metrics", ariaLabel: "Show runtime status strip", checked: isRuntimeStatusStripVisible, onChange: onRuntimeStatusStripVisibilityChange }) })] })] }));
