import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
export const SidebarPromptsList = ({ prompts, selectedPromptName, isLoadingPrompts, onSelectPrompt, onRefresh, onNewPrompt, activeTerminalId, onRestoreTerminal, onCloseTerminal, }) => {
    const userPrompts = useMemo(() => prompts.filter((p) => p.source === "user"), [prompts]);
    const builtinPrompts = useMemo(() => prompts.filter((p) => p.source === "builtin"), [prompts]);
    return (_jsxs("div", { className: "sidebar-prompts", children: [_jsxs("div", { className: "sidebar-prompts-toolbar", children: [_jsx("button", { type: "button", className: "sidebar-prompts-new-btn", onClick: onNewPrompt, children: "+ New Prompt" }), _jsx("button", { type: "button", className: "sidebar-prompts-refresh-btn", onClick: onRefresh, disabled: isLoadingPrompts, "aria-label": "Refresh prompts", children: "\u21BB" })] }), isLoadingPrompts && prompts.length === 0 ? (_jsx("p", { className: "sidebar-prompts-empty", children: "Loading..." })) : prompts.length === 0 ? (_jsx("p", { className: "sidebar-prompts-empty", children: "No prompts yet" })) : (_jsxs("div", { className: "sidebar-prompts-list", children: [userPrompts.length > 0 && (_jsxs("div", { className: "sidebar-prompts-group", children: [_jsx("h4", { className: "sidebar-prompts-group-label", children: "My Prompts" }), userPrompts.map((p) => (_jsxs("button", { type: "button", className: "sidebar-prompts-item", "data-active": selectedPromptName === p.name ? "true" : undefined, onClick: () => {
                                    onSelectPrompt(p.name);
                                }, children: [p.name, ".md"] }, p.name)))] })), builtinPrompts.length > 0 && (_jsxs("div", { className: "sidebar-prompts-group", children: [_jsx("h4", { className: "sidebar-prompts-group-label", children: "Built-in" }), builtinPrompts.map((p) => (_jsxs("button", { type: "button", className: "sidebar-prompts-item", "data-active": selectedPromptName === p.name ? "true" : undefined, onClick: () => {
                                    onSelectPrompt(p.name);
                                }, children: [p.name, ".md"] }, p.name)))] }))] })), activeTerminalId && (_jsxs("div", { className: "sidebar-prompts-minimized-terminal", children: [_jsxs("button", { type: "button", className: "sidebar-prompts-minimized-terminal-restore", onClick: onRestoreTerminal, children: [_jsx("span", { className: "sidebar-prompts-minimized-terminal-icon", children: ">_" }), _jsx("span", { className: "sidebar-prompts-minimized-terminal-label", children: "Prompt Engineer" })] }), _jsx("button", { type: "button", className: "sidebar-prompts-minimized-terminal-close", onClick: onCloseTerminal, "aria-label": "Close terminal", children: "\u2715" })] }))] }));
};
